env:
  node: true
  browser: true
  es6: true

extends:
- eslint:recommended
- plugin:react/recommended
- plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: "latest"
  sourceType: "module"

plugins:
- "react"
- "@typescript-eslint"

rules:
  react/jsx-uses-react: 0
  react/react-in-jsx-scope: 0
  sort-imports:
    - 1
    - allowSeparatedGroups: true

settings:
  react:
    version: "detect"
